export const appConfig = {
  appName: "UV Guard",
  storeName: "UV Guard: UV Index Tracker",
  tagline: "Plan your sun time with confidence.",
  description:
    "Track UV, sun exposure, tanning sessions, and sunscreen reminders with WeatherKit-backed forecasts.",
  iosUrl: "https://apps.apple.com/app/id6777101064",
  androidUrl: "https://play.google.com/store/apps/details?id=com.appfactory.uvguard",
  company: "App Factory Labs",
  supportPath: "/support",
  supportApiPath: "/api/support",
  privacyPath: "/privacy",
  termsPath: "/terms",
  screenshotPath: "/assets/uv-guard-home.png",
  iconPath: "/assets/icon.png",
  primaryColor: "#ffd735",
  accentColor: "#ff6b35",
  skyBlue: "#168bff",
  effectiveDate: "May 27, 2026",
} as const;
